name: Test Vyn Package Collector

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Vyn Package Collector
        run: |
          .\collector\vyn-collector.exe